MyTraveler/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('login_signup.urls')),
    url(r'^', include('timeline.urls'))
]

login_signup/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^login/$', 'login_signup.views.log_in', name='login'),
    url(r'^signup/$', 'login_signup.views.signup', name='signup'),
    url(r'^verification/(.*)$', 'login_signup.views.verify', name='verification'),
    url(r'^forgot_step_1$', 'login_signup.views.forgot_password_1', name='fpw1'),
    url(r'^forgot_step_2/(.*)/(\d+)$', 'login_signup.views.forgot_password_2', name='fpw2'),
]

timeline/urls.py
from django.conf.urls import include, url
from MyTraveler.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^timeline/$', 'timeline.views.show_timeline', name='timeline'),
    url(r'^logout/$', 'timeline.views.log_out', name='logout'),
    url(r'^profile$', 'timeline.views.show_profile', name='profile'),
    url(r'^board/(\d+)$', 'timeline.views.show_board', name='board'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, }),
]

login_signup/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.forms.widgets import TextInput, PasswordInput, RadioSelect

class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if 'required' in field.error_messages:
                field.error_messages['required'] = 'Please fill this field!'

    username = forms.CharField(label='', widget=TextInput(attrs={'class': 'input', 'id': 'email', 'name': 'email',
                                                                 'type': 'text', 'placeholder': 'Email or Username'}))

    password = forms.CharField(label='', widget=PasswordInput(attrs={'class': 'input', 'id': 'pass', 'name': 'password',
                                                                     'type': 'password', 'placeholder': 'Password'}))


class SignupForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if name != 'gender':
                if 'required' in field.error_messages:
                    field.error_messages['required'] = 'Please fill this field!'

    CHOICES = [('Male', 'Male'), ('Female', 'Female')]
    name = forms.CharField(label='', widget=TextInput(attrs={'type': 'text',
                                                             'placeholder': 'Full name (first and last)',
                                                             'class': 'input'}))

    age = forms.IntegerField(label='', widget=TextInput(attrs={'type': 'text',
                                                               'placeholder': 'Age',
                                                               'class': 'input'}),
                             error_messages={'invalid': 'This field should be number?!'})

    email = forms.CharField(label='', widget=TextInput(attrs={'type': 'text',
                                                              'placeholder': 'Email',
                                                              'class': 'input'}))

    password = forms.CharField(label='', widget=PasswordInput(attrs={'type': 'password',
                                                                     'placeholder': 'Password',
                                                                     'class': 'input'}))

    confirm = forms.CharField(label='', widget=PasswordInput(attrs={'type': 'password',
                                                                    'placeholder': 'Confirm Password',
                                                                    'class': 'input'}))

    gender = forms.ChoiceField(label='', choices=CHOICES, widget=RadioSelect(), error_messages={
                                                                           'required': 'Please select your gender!'})

    def clean_email(self):
        try:
            validate_email(self.cleaned_data['email'])
        except:
            raise ValidationError('Entered email is not valid!')

        return self.cleaned_data['email']

    def clean_age(self):
        value = self.cleaned_data['age']

        if value < 10 or value > 200:
            raise ValidationError('Age should be between 10 and 120!')

        return self.cleaned_data['age']

    def clean(self):
        if self.data['password'] != self.data['confirm']:
            raise ValidationError('Entered passwords do not match')

        return self.cleaned_data


class forgot1(forms.Form):
    email = forms.EmailField(label='', widget=TextInput(attrs={'placeholder': 'Email', 'type': 'text',
                                                               'class': 'input'}))


class forgot2(forms.Form):
    new_password = forms.CharField(label='', widget=PasswordInput(attrs={'placeholder': 'New password',
                                                                         'class': 'input'}))
    confirm_password = forms.CharField(label='', widget=PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                             'class': 'input'}))

    def clean(self):
        if self.data['new_password'] != self.data['confirm_password']:
            raise ValidationError('Entered passwords do not match!')

        return self.cleaned_data

login_signup/views.py
from random import randint
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.core.validators import validate_email
from django.http.response import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from login_signup.forms import SignupForm, LoginForm, forgot1, forgot2
from normaluser.models import NormalUser, VerificationCode

# Create your views here.

def log_in(request):
    if request.method == 'GET':
        return render(request, 'sign-in.html', {'form': LoginForm})

    else:
        form = LoginForm(request.POST)

        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])

            if user is not None:
                if user.is_active == False:
                    return HttpResponseRedirect(reverse('verification', args=[user.email]))

                else:
                    login(request, user)
                    return HttpResponseRedirect(reverse('timeline'))

            else:
                form.add_error(None, 'Entered username or password is wrong')
                return render(request, 'sign-in.html', {'form': form})

        else:
            return render(request, 'sign-in.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            newUser = NormalUser()

            try:
                _newUser = User.objects.create_user(username=form.cleaned_data['email'],
                                                    password=form.cleaned_data['password'],
                                                    first_name=form.cleaned_data['name'],
                                                    email=form.cleaned_data['email'])
            except:
                form.add_error(None, 'Email "' + request.POST['email'] + '" already existed')
                return render(request, 'sign-up.html', {'signupForm': form})

            _newUser.is_active = False

            newUser.user = _newUser
            newUser.age = form.cleaned_data['age']
            # newUser.birthDate.year = (datetime.datetime.now().year - form.cleaned_data['age'])
            newUser.gender = form.cleaned_data['gender']
            newUser.save()

            code = generate_verification_code()

            verifCode = VerificationCode()
            verifCode.code = code
            verifCode.user = _newUser
            verifCode.save()

            send_mail('Traveler', 'Hello ' + newUser.user.first_name + '\n\n Your verification code is ' + code +
                      '.\n click on the link below to verify your email address: \n\n' +
                      reverse('verification', args=[newUser.user.email])
                      , 'travellerbot@gmail.com', recipient_list=[newUser.user.email])

            return HttpResponseRedirect(reverse('verification', args=[newUser.user.email]))

        else:
            return render(request, 'sign-up.html', {'signupForm': form})

    else:
        form = SignupForm()
        return render(request, 'sign-up.html', {'signupForm': form})


def verify(request, email):
    if request.method == 'GET':
        return render(request, 'verification-code.html', {})

    else:
        try:
            validate_email(email)

        except:
            raise ValidationError('Wrong URL!')


        currUser = get_object_or_404(User, email=email)
        code = get_object_or_404(VerificationCode, user=currUser)

        if request.POST['verifier'] == code.code:
            currUser.is_active = True
            code.delete()
            return HttpResponseRedirect(reverse('login'))

        else:
            return render(request, 'verification-code.html', {'error': 'Wrong verification code!'})


def forgot_password_1(request):
    if request.method == 'GET':
        return render(request, 'fpw_1.html', {'form': forgot1()})

    else:
        form = forgot1(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']

            try:
                currUser = User.objects.get(email=email)
            except:
                return render(request, 'fpw_1.html', {'form': form, 'error': 'No such email exist'})

        else:
            return render(request, 'fpw_1.html', {'form': form, 'error': 'Entered email is not valid'})


        if currUser.is_active:
            try:
                tmpVerifCode = VerificationCode.objects.get(user=currUser)
            except:
                tmpVerifCode = None

            if tmpVerifCode is not None:
                tmpVerifCode.delete()

            verifCode = VerificationCode()
            verifCode.user = currUser
            verifCode.code = generate_verification_code()
            verifCode.save()

            send_mail('Traveler', 'Hello ' + currUser.first_name + '\n\n You can reset your password by clicking on '
                                           + 'link below: \n\n http://127.0.0.1:8000' +
                      reverse('fpw2', args=[email, verifCode.code]),
                      'travellerbot', [email])

            return render(request, 'fpw_1.html', {'form': form, 'success': 'Check your email address, an email ' +
                                                                           'containing a link to change your password '
                                                                           + 'has sent to you '})
        else:
            return render(request, 'fpw_1.html', {'form': form, 'error': 'Your account is not enable yet!'})


def forgot_password_2(request, email, code):
    if request.method == 'GET':
        return render(request, 'fpw_2.html', {'form': forgot2})

    else:
        form = forgot2(request.POST)

        if form.is_valid():
            try:
                currUser = User.objects.get(email=email)
            except:
                raise Http404

        else:
            return render(request, 'fpw_2.html', {'form': form, 'error': 'Entered password do not match'})


        verifCode = get_object_or_404(VerificationCode, user=currUser)

        if verifCode.code == code:
            currUser.set_password(request.POST['new_password'])
            currUser.save()
            verifCode.delete()
            return HttpResponseRedirect(reverse('login'))

        else:
            raise ValidationError("It seems that you're cheating or something! :D")




# extra functions

def generate_verification_code():
    code = ''
    
    for i in range(0,12):
        code += str(randint(0, 9))

    return code

login_signup/templates/fpw_1.html
{% load static %}
<!DOCTYPE html>

<html>
<head>
	<meta charset="utf-8">
	<title></title>

	<link href="{% static 'css/fpw-style.css' %}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'libraries/popup.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'libraries/transition.css' %}">

</head>
<body>
	<div class="wrapper first">
		<h1>First Step!</h1>
		<p>
			Please fill the field below with your email address, you will get your verification code.
		</p>

		<form action="" method="post" id="email_form">
            {% csrf_token %}
                {% for field in form %}
                    {{ field }}
                {% endfor %}
			<input type="submit" id="submit" value="Verify">
		</form>
		<a href="{% url 'login' %}">Get me to sign in</a>
	</div>

	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/fpw-ajax.js' %}"></script>
	<script type="text/javascript" src="{% static 'libraries/popup.js' %}"></script>
	<script type="text/javascript" src="{% static 'libraries/transition.js' %}"></script>

    <script>
        {% if error != '' %}
            $(".input[name='email']").popup({
                content : '{{ error }}',
                position: "right center",
                on : "manual",
                hideOnScroll: false
            });
            $(".input[name='email']").popup("show");
            $(".content").css('color', 'red')
        {% endif %}

        {% if success != '' %}
            $('.wrapper.first').popup({
                content : '{{ success }}',
                position: "right center",
                on : "manual",
                hideOnScroll: false
            });

            $('.wrapper.first').popup("show");
        {% endif %}
    </script>
</body>
</html>

login_signup/templates/fpw_2.html
{% load static %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link href="{% static 'css/fpw-style.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'libraries/popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'libraries/transition.css' %}">
</head>
<body>
    <div class="wrapper second">
		<h1>Second Step!</h1>

		<form action="" method="post" id="verif_form">
            {% csrf_token %}
			{% for field in form %}
                {{ field }}
            {% endfor %}
			<input type="submit" id="submit" value="Set">
		</form>
		<a href="sign-in.html">Get me to sign in</a>
	</div>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/fpw-ajax.js' %}"></script>
	<script type="text/javascript" src="{% static 'libraries/popup.js' %}"></script>
	<script type="text/javascript" src="{% static 'libraries/transition.js' %}"></script>

    <script>
        {% if error != '' %}
            $('.wrapper.second').popup({
                content : '{{ error }}',
                position: "right center",
                on : "manual",
                hideOnScroll: false
            });

            $('.wrapper.second').popup("show");
            $('.content').css('color', 'red')
        {% endif %}

    </script>
</body>
</html>

login_signup/templates/sign-in.html
{% load static %}
<!DOCTYPE html>

<html>
<head>
	<meta charset="utf-8">
	<title>Sign in to Traveler</title>

	<link href="{% static 'css/sign-in-style.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/normalize.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'libraries/popup.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'libraries/transition.css' %}">

</head>
<body>
	
	<div id="main">
		<div id="logo">
			Traveler
		</div>
		
		<div id="wrapper">
			<h1>Log in as normal member</h1>

			<form action="" method="post">
                {% csrf_token %}
				{% for field in form %}
                    <p> {{ field }} </p>
                {% endfor %}
				<p><input id="submit" type="submit" value="Log in"></p>
			</form>
			
			<div id="navigator">
				<a href="{% url 'signup' %}">Sign up</a>
				<a href="{% url 'fpw1' %}">Forgot the password?!</a>
			</div>
			
			<p id="busin"><a href="business.html">Login as business!</a></p>
			
		</div>
		
		<footer>
			<a href="about.html">About Traveler</a>
			<a href="terms.html">Terms & Privacy</a>
			<a href="android-app.html">Android App</a>
			<a href="business.html">Business</a>
			<a href="help.html">Help</a>
			<a href="yumb.html">Yumb</a>
		</footer>
		
	</div>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'libraries/popup.js' %}"></script>
	<script type="text/javascript" src="{% static 'libraries/transition.js' %}"></script>

    <script>
        {% for field in form %}
            {% for error in field.errors %}
                $("input[name='{{ field.name }}']").popup({
                    content : '{{ error }}',
                    position: "right center",
                    on : "manual",
                    hideOnScroll: false
                });
            {% endfor %}

            $('input[name="{{ field.name }}"]').popup("show");
        {% endfor %}


        {% for error in form.non_field_errors %}
            $("#wrapper").popup({
                    content : '{{ error }}',
                    position: "right center",
                    on : "manual",
                    hideOnScroll: false
                });
            $("#wrapper").popup('show');
{#            $('.content').css('position', 'relative');#}
            $('.ui.popup').css('top', '267px')
        {% endfor %}

        $('.content').css('color', 'red');
        $('.content').css('text-align', 'center')

    </script>
</body>
</html>

login_signup/templates/sign-up.html
{% load static %}
<!DOCTYPE html>

<html>
<head>
	<meta charset="utf-8">
	<title>Sign up at Traveler</title>

	<link href="{% static 'css/normalize.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/sign-up-style.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'libraries/popup.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'libraries/transition.css' %}">

</head>
<body>

	<div id="main">
		<div id="logo">
			Traveler
		</div>
		
		<div id="wrapper">
			<h1>Be a normal member</h1>
			
			<form action="{% url 'signup' %}" method="post">
            {% csrf_token %}
            {% for error in signupForm.non_field_errors %}
                {{ error }}
            {% endfor %}
                {% for field in signupForm %}
{#                    {% for error in field.errors %}#}
{#                        {{ error }}#}
{#                    {% endfor %}#}
                    {% if field.name != 'age' %}
                        {{ field }}
                    {% else %}
                        {{ field }} <br/>
                    {% endif %}
                {% endfor %}

				<input value="Get in!" type="submit" id="submit">
			</form>

			<a href="{% url 'login' %}" id="getback">I have an account</a><br>
			<a href="" id="busin">Be a business member</a>

			<p id="terms">Creating an account means you’re okay with Traveler's <a href="terms.html">Terms & Privacy</a>, so make sure u have read it.</p>
        </div>

		<footer>
			<a href="about.html">About Traveler</a>
			<a href="terms.html">Terms & Privacy</a>
			<a href="android-app.html">Android App</a>
			<a href="business.html">Business</a>
			<a href="help.html">Help</a>
			<a href="yumb.html">Yumb</a>
		</footer>
	</div>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'libraries/popup.js' %}"></script>
	<script type="text/javascript" src="{% static 'libraries/transition.js' %}"></script>

	<script type="text/javascript">

        {% for field in signupForm %}
            {% for error in field.errors %}
                {% if field.name == 'age' or field.name == 'password'%}
                    $("input[name='{{ field.name }}']").popup({
                        content : '{{ error }}',
                        position: "right center",
                        on : "manual",
                        hideOnScroll: false
                    });
                {% endif %}

                {% if field.name == 'name' or field.name == 'confirm' or field.name == 'email' %}
                    $("input[name='{{ field.name }}']").popup({
                        content : '{{ error }}',
                        position: "left center",
                        on : "manual",
                        hideOnScroll: false
                    });
                {% endif %}
            {% endfor %}
            $('input[name="{{ field.name }}"]').popup("show");
        {% endfor %}

        {% for field in signupForm %}
            {% if field.name == 'gender' %}
                {% for error in field.errors %}
                    $("#id_gender").popup({
                            content : '{{ error }}',
                            position: "right center",
                            on : "manual",
                            hideOnScroll: false
                        });
                    $('#id_gender').popup("show");
                {% endfor %}
            {% endif %}
        {% endfor %}
{##}
{#		$('input[name="name"]').popup({#}
{#		    content : 'Hello I am a popup',#}
{#		    position: "left center",#}
{#		    on : "manual"#}
{#		  });#}
{##}
{#		$('input[name="name"]').popup("show");#}
{##}
{#		$('input[name="email"]').popup({#}
{#		    content : 'Hello I am a popup',#}
{#		    position: "right center",#}
{#		    on : "manual"#}
{#		  });#}
{##}
{#		$('input[name="email"]').popup("show");#}
{##}
{#		$('input[name="password"]').popup({#}
{#		    content : 'Hello I am a popup',#}
{#		    position: "left center",#}
{#		    on : "manual"#}
{#		  });#}
{##}
{#		$('input[name="password"]').popup("show");#}
{##}
{#		$('input[name="confirm"]').popup({#}
{#		    content : 'Hello I am a popup',#}
{#		    position: "right center",#}
{#		    on : "manual"#}
{#		  });#}
{##}
{#		$('input[name="confirm"]').popup("show");#}
{##}
{#		$("form ul").css({#}
{#			"border" : "1px solid red"#}
{#		});#}
	</script>
</body>
</html>

login_signup/templates/verification-code.html
{% load static %}
<!DOCTYPE html>

<html>
	<head>
		<title>Verification</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/succeed-style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'libraries/popup.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'libraries/transition.css' %}">

	</head>

	<body>
		<div id="wrapper">
			<h1>Just a few steps..</h1>

			<p>
				Check your email address, an email containing your verification code has been sent to you.
				<br>
				Please fill the field below with your verification code.
			</p>

			<form action="" method="post" id="verif-form">
                {% csrf_token %}
				<input type="text" placeholder="Verification code" name="verifier" id="verif"><br>
				<input type="submit" value="Verify" id="submit">
			</form>
		</div>
	</body>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'libraries/popup.js' %}"></script>
	<script type="text/javascript" src="{% static 'libraries/transition.js' %}"></script>
    <script>
        {% if error != '' %}
            $("#verif").popup({
                    content : '{{ error }}',
                    position: "right center",
                    on : "manual",
                    hideOnScroll: false
                });
            $('#verif').popup("show");
        {% endif %}

        $('.content').css('color', 'red');

    </script>
</html>